MBCART/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin

admin.site.site_header = 'MBCART'
admin.site.index_title = 'Welcome User'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('profile/',include("UserProfile.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    path('', views.index, name="ShopHome"),
    path('about', views.about, name="About"),
    path('cart', views.cart, name="Cart"),
    path('signup', views.signup, name="signup"),
    path('signin', views.signin, name="signin"),
    path('signout', views.signout, name="signout"),
    path('submitReview', views.submitReview, name="submitReview"),
    path('searchResult', views.search, name="search"),
    path('product/<int:id>', views.product_desc, name="product_desc"),
    path('AddToCart/<int:id>', views.AddToCart, name="addtocart"),
    path('liked', views.liked, name="liked"),
    path('disliked', views.disliked, name="disliked"),
    path('removecartitem', views.removecartitem, name="removecartitem"),
    path('category/<str:string>', views.category, name="category_desc"),
    path('subcategory/<str:string>', views.subcategory, name="sub_cat_desc"),
    path('getCartItems', views.getCartItems, name="getCartItems"),
    path('payment', views.payment, name="payment"),
    path('getMyRecentSearchItems', views.getMyRecentSearchItems,name="getMyRecentSearchItems"),
    path('search', views.search_product,name="search_product"),
    path('FAQ', views.faq,name="faq"),
    path('compare',views.compareview,name="Compare"),
    path('add_compare_item',views.add_compare_item,name="add_compare_item"),
    path('similar_products',views.show_similar_products,name='similar_products'),
    path('notifications_viewed',views.notifications_viewed,name='notifications_viewed'),
    path('chatbot/',views.chatbot_response,name='chatbot_response'),
]

UserProfile/models.py
from shop import models as model
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver


class Address(models.Model):
    user = models.ForeignKey(model.User, on_delete=models.SET_DEFAULT, default=None)
    full_name = models.CharField(max_length=500)
    phone_number = models.CharField(max_length=20)
    alternate_phone_number = models.CharField(max_length=20)
    pincode = models.CharField(max_length=20)
    state = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    house_no = models.CharField(max_length=200)
    area = models.CharField(max_length=500)
    home_work_address = models.BooleanField(default=True)
    # true means home and false means work
    default_address = models.BooleanField(default=False)

    def __str__(self):
        return str(self.full_name)


class Order(models.Model):
    product = models.ForeignKey(
        model.Product, on_delete=models.SET_DEFAULT, default=None
    )
    address = models.ForeignKey(Address, on_delete=models.SET_DEFAULT, default=None)
    user = models.ForeignKey(
        model.User,
        on_delete=models.SET_DEFAULT,
        default=None,
        related_name="orders",
    )
    quantity = models.IntegerField(default=1)
    order_date = models.DateTimeField(auto_now_add=True)
    shipped = models.BooleanField(default=False)
    shipped_date = models.DateField(null=True,blank=True)
    outfordelivery = models.BooleanField(default=False)
    outfordelivery_date = models.DateField(null=True,blank=True)
    delivered = models.BooleanField(default=False)
    delivered_date = models.DateField(null=True,blank=True)
    final_price = models.IntegerField(default=0)
    payment_id = models.CharField(max_length=150, null=False)
    order_id = models.CharField(max_length=150,  null=False)
    signature = models.CharField(max_length=150, null=False)
    canceled = models.BooleanField(default=False)

    def __str__(self):
        return str(self.product)

@receiver(post_save, sender=Order)
def do_something(sender, instance,created, **kwargs):
    if instance.canceled:
        n=Notification.objects.create(user=instance.user,notification=f"Your Product <a href='/profile/myorders'>{' '.join(instance.product.product_name.split(' ')[:5])+'...'}</a> has been Cancelled")
        n.save()
    elif instance.delivered:                                                               
        n=Notification.objects.create(user=instance.user,notification=f"Your Product <a href='/profile/myorders'>{' '.join(instance.product.product_name.split(' ')[:5])+'...'}</a> has been Delivered")
        n.save()
    elif instance.outfordelivery:
        print(instance.outfordelivery)
        n=Notification.objects.create(user=instance.user,notification=f"Your Product <a href='/profile/myorders'>{' '.join(instance.product.product_name.split(' ')[:5])+'...'}</a> has been Out For Delievery")
        n.save()
    elif instance.shipped:
        n=Notification.objects.create(user=instance.user,notification=f"Your Product <a href='/profile/myorders'>{' '.join(instance.product.product_name.split(' ')[:5])+'...'}</a> has been shipped Now")
        n.save()
    elif created:
        n=Notification.objects.create(user=instance.user,notification=f"Your Product <a href='/profile/myorders'>{ ' '.join(instance.product.product_name.split(' ')[:5])+'...' }</a> has been Ordered")
        n.save()

from datetime import datetime
class Notification(models.Model):
    user=models.ForeignKey(model.User,on_delete=models.CASCADE)
    notification=models.CharField(max_length=500)
    created_at=models.DateTimeField(auto_now_add=True)
    is_read=models.BooleanField(default=False)
    def how_old(self):
        date = self.created_at.replace(tzinfo=None)
        if (datetime.now()-date).total_seconds() < 3600:
            return f"{int((datetime.now() - date).total_seconds() // 60)}m"
        elif (datetime.now() - date).days < 1:
            return f'{int((datetime.now() - date).total_seconds()//3600)}h'
        elif (datetime.now() - date).days < 7:
            return f'{int((datetime.now() - date).total_seconds()//84600)}d'
        elif (datetime.now() - date).days < 30:
            return (datetime.now() - date).days//7
        elif (datetime.now() - date).days < 365:
            return (datetime.now() - date).days//30.5
        else:
            return (datetime.now() - date).days//365
        
    def __str__(self) -> str:
        return self.notification

shop/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from UserProfile.models import Address
from UserProfile.models import Order
from UserProfile.models import Notification
from .models import *
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.http import JsonResponse
from fuzzysearch import find_near_matches
from django.contrib import messages
from redmail import gmail

from shop.keys import gmailkey as gk
from django.core.mail import send_mail
from django.core.mail import EmailMessage
from django.template.loader import get_template
from django.http import HttpResponse, HttpResponseRedirect

from xhtml2pdf import pisa
import os


# Home Page
def index(request):
    products = Product.objects.all()
    coursal = Coursal.objects.all()
    productimg = ProductImages.objects.all()
    category = Category.objects.all()
    latest_laptops = (
        Product.objects.filter(Category_id=5).order_by("-product_publish_date").values()
    )
    latest_mobiles = (
        Product.objects.filter(Category_id=1).order_by("-product_publish_date").values()
    )
    latest_headphones = (
        Product.objects.filter(Category_id=2).order_by("-product_publish_date").values()
    )
    cart = ""
    if request.user.is_authenticated:
        cart = Cart.objects.filter(user=request.user)
    params = {
        "product": products,
        "coursal": coursal,
        "thumbnail": productimg,
        "cart": cart,
        "category": category,
        "latest_laptops": latest_laptops,
        "latest_mobiles": latest_mobiles,
        "latest_headphones": latest_headphones,
    }

    if request.COOKIES.get("recentitems"):
        recent_items = eval(request.COOKIES.get("recentitems"))
        params["recent_items"] = recent_items[3::-1]

    if request.COOKIES.get("recentsearch"):
        recent_search = eval(request.COOKIES.get("recentsearch"))
        params["recent_search"] = recent_search[3::-1]

    return render(request, "shop/index.html", params)


#  Search functionality using fuzzysearch module
# tries to match the patterns and return response
def search(request):  
    query = request.GET.get("search", "")
    query = query.strip()
    ids = set()
    query = query.lower().replace(" ", "")

    if query == "":
        return index(request)

    category = Category.objects.all()
    subcat = SubCategory.objects.all()
    products = Product.objects.all()
    for cat in category:
        s = find_near_matches(query, cat.name.lower(), max_l_dist=1)
        if s != []:
            product = Product.objects.filter(Category_id=cat.id)
            for i in product:
                ids.add(i.product_id)

    for sc in subcat:
        s = find_near_matches(query, sc.name.lower(), max_l_dist=1)
        if s != []:
            product = Product.objects.filter(Sub_Category_id=sc.id)
            for i in product:
                ids.add(i.product_id)

    if not ids:
        for product in products:
            split_names = product.product_name.split(" ")
            split_names = split_names
            for word in split_names:
                s = find_near_matches(query, word.lower(), max_l_dist=1)
                if s != []:
                    ids.add(product.product_id)

        for product in products:
            split_names = product.product_desc.split(" ")
            split_names = split_names
            for word in split_names:
                s = find_near_matches(query, word.lower(), max_l_dist=1)
                if s != []:
                    ids.add(product.product_id)

    # Only the result objects
    qs = Product.objects.none()
    for i in ids:
        qs = qs | Product.objects.filter(product_id=i)

    params = {"query": query, "ids": ids, "product": qs}
    response = render(request, "shop/searchResult.html", params)
    # For recent search items
    # response.delete_cookie('recentsearch')
    if not request.COOKIES.get("recentsearch"):
        response.set_cookie("recentsearch", str(list(ids)))
    else:
        arr = eval(request.COOKIES.get("recentsearch"))
        for i in ids:
            if i not in arr:
                arr.append(i)
        response.set_cookie("recentsearch", str(arr))

    return response


def compareview(request):
    ids = eval(request.COOKIES.get("CompareValues"))
    prods = Product.objects.filter(product_id__in=ids)

    samecategory = Product.objects.filter(Category_id=prods.first().Category_id)
    params={'compareproductlist':prods,
            'sc':samecategory,}
    return render(request,'shop/compare.html',params)

def add_compare_item(request):
    item_id = request.GET.get('item')
    ids = eval(request.COOKIES.get("CompareValues"))
    prods = Product.objects.filter(product_id__in=ids)
    category = prods.first().Category
    for i in prods:
        if i.Category!= category:
            return JsonResponse({"is_valid": False})
    return JsonResponse({"is_valid":True})

# About section page
def about(request):
    return render(request, "shop/about.html")


# profuct Description page
def product_desc(request, id):
    product = Product.objects.get(product_id=id)
    sub_cat = SubCategory.objects.get(id=product.Sub_Category_id)
    if not request.user:
        my_orders=Order.objects.filter(user=request.user).values_list(flat=True)
    my_orders=""
    samecategory = (Product.objects.filter(Category_id=product.Category_id)).exclude(
        product_id=id
    )
    desc = product.product_desc
    desc = desc.split("\n")
    

    what_is_in_the_box = product.what_is_in_the_box
    what_is_in_the_box = what_is_in_the_box.split("\n")

    Reviews = Review.objects.filter(product=product)
    user_review = Reviews.filter(user_id=request.user.id)

    is_added_to_cart = False

    if request.user.is_authenticated:
        cart = Cart.objects.filter(user=request.user)
        for item in cart:
            if product == item.product:
                is_added_to_cart = True

    total_ratings = sum(r.rating for r in Reviews)
    product_rating = total_ratings / len(Reviews) if len(Reviews) > 0 else 0
    product.product_rating = product_rating
    product.save(force_update=True)
    
    
    if request.COOKIES.get("CompareValues"):
        compare_items = eval(request.COOKIES.get("CompareValues"))
        prods = Product.objects.filter(product_id__in=compare_items)
    else:
        prods=[]
    
    params = {
        "compare_items":prods,
        "product": product,
        "sc": samecategory,
        "user_review": user_review,
        "sub_cat": sub_cat,
        "is_added_to_cart": is_added_to_cart,
        "aboutthisitem": desc,
        "what_is_in_the_box": what_is_in_the_box,
        "my_orders":my_orders,
    }

    response = render(request, "shop/product_desc.html", params)

    # For recent viewed items
    # response.delete_cookie('recentitems')
    arr = (
        eval(request.COOKIES.get("recentitems"))
        if request.COOKIES.get("recentitems")
        else []
    )
    arr.append(product.product_id)
    response.set_cookie("recentitems", str(arr))
    return response


# Cart page
def AddToCart(request, id):
    if request.method == "GET":
        product = Product.objects.get(product_id=id)
        cartitem, is_added = Cart.objects.get_or_create(
            user=request.user, product=product, totalprice=product.product_price
        )
        messages.success(request, "Item Successfully Added To Cart")
        getCartItems(request)
        return HttpResponseRedirect(request.META.get("HTTP_REFERER"))


# Fetch request to add an item to cart

# def AddToCart(request, id):
#     if request.method == "GET":
#         product = Product.objects.get(product_id=id)
#         cartitem, is_added = Cart.objects.get_or_create(
#             user=request.user, product=product, totalprice=product.product_price
#         )
#         messages.success(request, "Item Successfully Added To Cart")
#         getCartItems(request)
#         return JsonResponse("True", safe=False)


def removecartitem(request):
    if request.method == "POST":
        item = request.POST["id"]
        Cart.objects.filter(id=item).delete()
        messages.error(request, "Item Successfully Removed From Cart")
    return HttpResponseRedirect(request.META.get("HTTP_REFERER"))


def cart(request):
    cartitems = Cart.objects.filter(user=request.user)
    params = {
        "cartitems": cartitems,
    }
    return render(request, "shop/cart.html", params)


def signup(request):
    if request.method == "POST":
        # we can also write like this
        # username=request.POST['username']
        username = request.POST.get("username")
        fname = request.POST.get("fname")
        lname = request.POST.get("lname")
        email = request.POST.get("email")
        password = request.POST.get("password")

        if User.objects.filter(username=username):
            messages.error(request, "The Username has already been taken !")
            return HttpResponseRedirect(request.META.get("HTTP_REFERER"))

        try:
            myuser = User.objects.create_user(username, email, password)
            myuser.first_name = fname
            myuser.last_name = lname
            myuser.save()
            messages.success(request, "Your Account has been successfully created.")
        except Exception as e:
            messages.error(request, "Something went wrong try again later !")
    return HttpResponseRedirect(request.META.get("HTTP_REFERER"))


# Sign in and Signout functions to sign in or out


def signin(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, "Successfully Logged In")

        else:

templates/shop/about.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>About</title>
    <style>
      * {
        user-select: none;
        padding: 0;
        font-family: Verdana, Geneva, Tahoma, sans-serif;
        margin: 0;
      }

      body {
        height: 100vh;
        display: flex;
        justify-content: center;
        align-items: center;
        background-image: url("https://wallpapercave.com/wp/wp3537549.jpg");
        background-position: center;
        background-size: cover;
      }

      #container {
        height: 500px;
        width: 900px;
        background: rgba(37, 28, 28, 0.103);
        box-shadow: 0 8px 32px 0 rgb(17, 13, 13);
        backdrop-filter: blur(20px);
        border-radius: 10px;
        border: 5px solid rgba(255, 255, 255, 0.678);
        display: flex;
        justify-content: center;
        align-items: center;
        flex-flow: column;
      }

      #h1 {
        color: rgba(206, 206, 206, 0.89);
        margin-bottom: 50px;
        font-size: 60px;
        font-weight: 100;
        font-weight: 900;
      }

      p {
        padding: 0px 20px;
        font-size: 20px;
        text-align: center;
        color: rgba(255, 255, 255, 0.808);
        line-height: 40px;
      }
    </style>
  </head>

  <body>
    <div id="container">
      <div id="h1">MBCART</div>
      <p>
        &nbsp;Welcome to our college project ecommerce website! <br />
        We hope you enjoy your shopping experience with us!
        <br />
        Note: As this is a college project, please keep in mind that the website
        may not be fully operational and some features may be limited.
      </p>
    </div>
  </body>
</html>

templates/shop/index.html
{% extends 'shop/basic.html' %} 
{%block title%}MBCART{%endblock title%} 
{% block position %}position-sticky{% endblock position %} 
{%block body%} 
{%load static%}
{% load humanize %} 

<div style="background-color::#EAEDED;" >
    <!-- Offer Coursal -->
    <div id="carouselExampleControls" class="carousel slide p-0" data-bs-ride="carousel">
        <div class="carousel-inner">
            {% for j in coursal|slice:":3" %}
            <div class="carousel-item  {% if forloop.first %}active{% endif %}">
                <a href="{{j.image_url}}">
                    <img src='/media/{{j.coursal_image}}' style="object-fit:cover;" class="d-block w-100" alt="...">
                </a>
            </div>
            {% endfor %}
        </div>
        <button class="carousel-control-prev" style="width:5%;" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
    </button>
        <button class="carousel-control-next" style="width:5%;" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
    </button>
    </div>

    <div class="container-xxl">
        <div class="row row-cols-1 row-cols-sm-3 row-cols-md-3 g-3 mt-1">
            {% if recent_search %}
            <div class="col">
                <div class="card rounded-0 shadow-sm px-3 pb-3">
                    <h6 style="font-weight: bold;" class="ps-2 mt-3">Recent Search</h6>
                    <div class="row">
                        {% for i in product %} 
                        {% if i.product_id in recent_search %}
                        <div class="col-md-6">
                            <a href="/product/{{i.product_id}}" style="display:grid;place-items: center;" class="text-decoration-none text-dark">
                                <img class="img-fluid" style="width:150px;height:150px;object-fit:contain;" src='/media/{{i.image}}' />
                                <small class="text-center  d-inline-block w-100">{{i.product_name|truncatechars:35}}</small>
                            </a>
                        </div>
                        <hr class="d-md-none " /> 
                        {% endif %} 
                        {% endfor %}
                    </div>
                </div>
            </div>
            {% endif %}

            {% if cart.count > 0 %}
            <div class="col">
                <div class="card shadow-sm rounded-0 px-3 pb-3">
                    <h6 style="font-weight: bold;" class="ps-2 mt-3">Pending in Cart</h6>
                    <div class="row">
                        {% for i in cart|slice:":4" %}
                        <div class="col-md-6">
                            <a href="/cart" style="display:grid;place-items: center;">
                                <img class="img-fluid" style="width:150px;height:150px;object-fit:contain;" src='/media/{{i.product.image}}' />
                            </a>
                            <small class="text-center d-inline-block w-100">{{i.product.product_name|truncatechars:35}}</small>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            {% endif %}


            {% comment %} Seller Dashboard Under Construction {% endcomment %}
            {% comment %} <div class="col">
                <div class="sell_on_mbcart card shadow-sm rounded-0 p-3 pb-3">
                    <div class="row">
                        <div class="col-12">
                            <h5 class="fw-bolder ">Sell on MBCART with 50% off on Selling Fee</h5>
                        </div>
                    </div>
                    <img class="seller_img" src="{% static 'static_images/seller.jpg' %}" alt="">
                    <small class="mt-1"><a href="/SellerDashboard" class="text-decoration-none " >Register now</a></small>
                </div>
            </div> {% endcomment %}

            <div class="col">
                <div class="card rounded-0 shadow-sm px-3 pb-3">
                    <h6 style="font-weight: bold;" class="ps-2 mt-3">Related to items you've viewed</h6>
                    <div class="row">
                        {% for i in product %} 
                        {% if i.product_id in recent_items %}
                        <div class="col-md-6">
                            <a href="/product/{{i.product_id}}" style="display:grid;place-items: center;" class="text-decoration-none text-dark">
                                <img class="img-fluid" style="width:150px;height:150px;object-fit:contain;" src='/media/{{i.image}}' alt='image' />
                                <small class="text-center  d-inline-block w-100">{{i.product_name|truncatechars:35}}</small>
                            </a>
                        </div>
                        <hr class="d-md-none " /> {% endif %} {% endfor %}
                    </div>
                </div>
            </div>
        </div>



        <div class="row row-cols-md-2 g-3 mt-1">
            <div class="col-12 col-md-8 ">
                <div class="card rounded-0 shadow-sm h-100 d-flex justify-content-center">
                    <div id="carouselExampleFade" class="carousel slide carousel-fade p-0" data-bs-ride="carousel2">
                        <div class="carousel-inner">
                            {% for j in coursal|slice:"3:" %}
                            <div class="carousel-item  {% if forloop.first %} active {% endif %}">
                                <a href="{{j.image_url}}" target="_blank">
                                    <img src='/media/{{j.coursal_image}}' style="object-fit:contain;" class="d-block w-100" alt="...">
                                </a>
                            </div>
                            {% endfor %}
                        </div>
                        <button class="carousel-control-prev" style="width:5%;" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="prev">
              <span class="carousel-control-prev-icon"  aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
                        <button class="carousel-control-next text-black" style="width:5%;" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
            </button>
                    </div>
                </div>
            </div>

            <div class="col-md-4 col-12">
                <div class="card rounded-0 shadow-sm px-3 pb-3">
                    <h6 style="font-weight: bold;" class="ps-2 mt-3">Shop by Category</h6>
                    <div class="row">
                        {% for i in category|slice:":4" %}
                        <div class="col-md-6">
                            <a href="/category/{{i.name}}" style="display:grid;place-items: center;" class="text-decoration-none text-dark">
                                <img class="img-fluid" style="height:180px;object-fit:contain;position: relative;top:0px" src="/media/{{i.image}}" />
                                <small class=" text-center d-inline-block w-100" style="position: relative;bottom:30px">{{i.name|truncatechars:35}}</small>
                            </a>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>


        <div class="row g-3 mt-1">
            <div class="col-12 col-sm-4 col-md-12">
                <div class="card shadow-sm rounded-0 px-3 pb-3 h-100">
                    <h6 style="font-weight: bold;" class="ps-2 mt-3">Latest Mobiles Arrivals</h6>
                    <div class="row">
                        {% for i in latest_mobiles|slice:":4" %}
                        <div class="col-md-3">
                            <a href="/product/{{i.product_id}}" style="display:grid;place-items: center;" class="text-decoration-none text-dark">
                                <img class="img-fluid" style="height:180px;object-fit:contain;" src='/media/{{i.image}}' />
                                <small class=" text-center d-inline-block w-100">{{i.product_name|truncatechars:35}}</small>
                            </a>
                        </div>
                        {% endfor %}
                    </div>

                </div>
            </div>

            <div class="col-12 col-sm-4 col-md-12">
                <div class="card shadow-sm rounded-0 px-3 pb-3 h-100">
                    <h6 style="font-weight: bold;" class="ps-2 mt-3">Latest Laptops Arrivals</h6>
                    <div class="row">
                        {% for i in latest_laptops|slice:":4" %}
                        <div class="col-md-3">
                            <a href="/product/{{i.product_id}}" style="display:grid;place-items: center;" class="text-decoration-none text-dark">
                                <img class="img-fluid" style="height:180px;object-fit:contain;" src='media/{{i.image}}' />
                                <small class=" text-center d-inline-block w-100">{{i.product_name|truncatechars:35}}</small>
                            </a>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>

            <div class="col-12 col-sm-4 col-md-12">
                <div class="card shadow-sm rounded-0 px-3 pb-3 h-100">
                    <h6 style="font-weight: bold;" class="ps-2 mt-3">Latest Headphones Arrivals</h6>
                    <div class="row">
                        {% for i in latest_headphones|slice:":4" %}
                        <div class="col-md-3">
                            <a href="/product/{{i.product_id}}" style="display:grid;place-items: center;" class="text-decoration-none text-dark">
                                <img class="img-fluid" style="height:180px;object-fit:contain;" src='media/{{i.image}}' />
                                <small class=" text-center d-inline-block w-100">{{i.product_name|truncatechars:35}}</small>
                            </a>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>


{% comment %} 
    <div class="container-xxl">
        <div class=" row g-3 mt-1">
            <div class="col-12">
                <div class="card rounded-0 shadow-sm h-100 d-flex justify-content-center">
                </div>
            </div>
        </div>
    </div>
    <!-- for additional boxes  -->
 {% endcomment %}



    <div class="container-xxl ">
        <!-- row-cols-1 row-cols-sm-3 row-cols-md-4 g-4 -->
        <div class="row">
            {% for i in product %}
            <div class="col col-sm-6 col-lg-4 col-xl-3 my-3 ">
                <div class="card shadow-sm" style="min-height:400px;">
                    <div class="mt-3">
                        <a href="/product/{{i.product_id}}" style="display:grid;place-items: center;">
                            <img class="" style="width:170px;height:170px;object-fit:contain;" src='media/{{i.image}}' />
                        </a>
                    </div>
                    <div class="card-body pt-xl-3 pt-md-1">
                        <p class="card-text p-0 m-0">
                            <div>
                                <a href="/product/{{i.product_id}}" style="display:inline-block;min-height:100px;text-decoration: none;text-align:center;">{{i.product_name|truncatechars:100}}</a>
                                <div class="text-center">
                                    <span class="text-bg-success" style="border-radius:5px;padding:2px 8px;font-size: 12px;margin-top:15px;display: inline-block;">{{i.product_rating}}
                                        <small style="position:relative;top: -1px;left:4px;font-size:9px;" class="bi bi-star-fill"></small>
                                    </span>
                                    <span>({{i.order_set.count}})</span>
                                </div>
                                <h6 class="blockquote mt-3 text-center">₹{{i.product_price|intcomma}} &nbsp;
                                    <strike class="text-muted ">
                                        <small>₹{{i.product_initial_price|intcomma}}</small>
                                    </strike>
                                </h6>
                            </div>
                        </p>
                        <div class="d-flex justify-content-center align-items-center">
                            <div class="btn-group w-100">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>

    </div>
</div>
{%endblock%}